baseURL = 'https://biswaone.github.io/'
languageCode = 'en-us'
title = 'Notes/Rambling of a 0x engineer'
theme = 'hugo-theme-nostyleplease'

[params]
  math = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
